In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from astropy.table import Table

In [2]:
file = "/home/astroinfo2023/users4astroinfo2023/arango/Gal_class/2023-sfh-galaxy-classification/data/Horizon_AGN-COSMOS_like/HorizonAGN_LAIGLE-DAVIDZON+2019_COSMOS_v1.6.fits"
df = Table.read(file)
df_physics = df.to_pandas()
df_physics.head()

,ID,RA_true,DEC_true,z_true,z_dist,MASS_true,MASSBC03_true,SFR_true,MASS-WEIGHTED_AGE_true,METALLICITY_true,...,ch3_TOT,ch3_TOT_ERR,ch3_TOTnoerr,ch4_TOT,ch4_TOT_ERR,ch4_TOTnoerr,SLICE1,NUM,SUBSAMPLE,ID_HZAGN
0,1,-0.486512,0.431009,0.999855,1.000129,10.104214,9.957056,1.35105,2.838124e+09,0.01530,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663,339,1,3
1,2,-0.274560,-0.390665,0.999877,0.999221,9.628185,9.494867,0.96779,1.769603e+09,0.00958,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663,341,1,4
2,3,-0.232123,-0.356485,0.999962,1.000609,9.142076,9.006433,0.30198,1.860397e+09,0.00699,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663,343,1,6
3,4,-0.302264,-0.354096,0.999992,0.999175,10.022016,9.882118,1.12829,2.130616e+09,0.01270,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663,344,1,7
4,5,-0.309356,-0.326307,0.999904,0.999518,9.192010,9.046213,0.14881,2.755331e+09,0.01047,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663,345,1,8

In [4]:
# read the csv file

file2 = "PCA_cluster_id.csv"

df = pd.read_csv(file2,sep=',')
df.head()

    id  PCA_projection_X  PCA_projection_Y  PCA_projection_Z  cluster
0  1.0         -1.839338         -0.199802          0.518364      0.0
1  2.0          1.455483          1.744388         -0.699344      1.0
2  3.0          0.951062          1.938859          0.560835      5.0
3  4.0         -1.145422          1.189617         -0.806234      3.0
4  5.0         -1.747621          0.864934          0.588313      0.0

In [6]:
df_combined = pd.merge(df, df_physics, left_on='id', right_on='ID', how='inner')
df_combined.describe()

,id,PCA_projection_X,PCA_projection_Y,PCA_projection_Z,cluster,ID,RA_true,DEC_true,z_true,z_dist,...,ch3_TOT,ch3_TOT_ERR,ch3_TOTnoerr,ch4_TOT,ch4_TOT_ERR,ch4_TOTnoerr,SLICE1,NUM,SUBSAMPLE,ID_HZAGN
count,91370.000000,9.137000e+04,9.137000e+04,9.137000e+04,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,...,91370.0,91370.0,91370.0,91370.0,91370.0,91370.0,91370.000000,91370.000000,91370.0,91370.000000
mean,48143.402638,1.275353e-15,3.957949e-15,-1.748167e-15,2.016417,48143.402638,-0.003259,-0.023749,0.783035,0.783028,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,12208.684426,1591.820412,1.0,436954.840123
std,27788.105334,1.481714e+00,1.121969e+00,9.727033e-01,1.718999,27788.105334,0.284615,0.290933,0.141022,0.141023,...,0.0,0.0,0.0,0.0,0.0,0.0,1107.295903,716.468450,0.0,252580.894221
min,1.000000,-1.992994e+00,-2.114617e+00,-1.988426e+00,0.000000,1.000000,-0.499997,-0.499977,0.500002,0.500129,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663.000000,48.000000,1.0,3.000000
25%,24102.250000,-1.423691e+00,-8.930986e-01,-7.593530e-01,0.000000,24102.250000,-0.246800,-0.276898,0.671467,0.671405,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,11224.000000,1093.000000,1.0,211772.250000
50%,48174.500000,-2.039903e-01,-1.279862e-01,-5.426631e-02,2.000000,48174.500000,-0.007432,-0.038050,0.785086,0.784541,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,12109.000000,1458.000000,1.0,458793.500000
75%,72382.750000,1.323275e+00,8.332806e-01,6.618572e-01,4.000000,72382.750000,0.247102,0.226185,0.909376,0.909553,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,13022.000000,1934.000000,1.0,652006.750000
max,96088.000000,2.894248e+00,2.772326e+00,2.885914e+00,5.000000,96088.000000,0.499997,0.499998,0.999995,1.000609,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,14682.000000,5500.000000,1.0,863794.000000

,ID,RA_true,DEC_true,z_true,z_dist,MASS_true,MASSBC03_true,SFR_true,MASS-WEIGHTED_AGE_true,METALLICITY_true,...,ch3_TOT,ch3_TOT_ERR,ch3_TOTnoerr,ch4_TOT,ch4_TOT_ERR,ch4_TOTnoerr,SLICE1,NUM,SUBSAMPLE,ID_HZAGN
count,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,91370.000000,9.137000e+04,91370.000000,...,91370.0,91370.0,91370.0,91370.0,91370.0,91370.0,91370.000000,91370.000000,91370.0,91370.000000
mean,48143.402638,-0.003259,-0.023749,0.783035,0.783028,9.714548,9.570715,1.335118,2.744314e+09,0.012022,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,12208.684426,1591.820412,1.0,436954.840123
std,27788.105334,0.284615,0.290933,0.141022,0.141023,0.506453,0.504224,2.379181,8.077516e+08,0.004123,...,0.0,0.0,0.0,0.0,0.0,0.0,1107.295903,716.468450,0.0,252580.894221
min,1.000000,-0.499997,-0.499977,0.500002,0.500129,9.000000,8.833046,0.000000,1.953301e+08,0.002460,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,10663.000000,48.000000,1.0,3.000000
25%,24102.250000,-0.246800,-0.276898,0.671467,0.671405,9.298635,9.156480,0.258082,2.173854e+09,0.008880,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,11224.000000,1093.000000,1.0,211772.250000
50%,48174.500000,-0.007432,-0.038050,0.785086,0.784541,9.621072,9.478066,0.560200,2.672318e+09,0.011460,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,12109.000000,1458.000000,1.0,458793.500000
75%,72382.750000,0.247102,0.226185,0.909376,0.909553,10.048704,9.904741,1.411290,3.248793e+09,0.014790,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,13022.000000,1934.000000,1.0,652006.750000
max,96088.000000,0.499997,0.499998,0.999995,1.000609,12.301133,12.135709,147.052900,6.400585e+09,0.034320,...,-99.0,-99.0,-99.9,-99.0,-99.0,-99.9,14682.000000,5500.000000,1.0,863794.000000